[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qfl-robotics"
version = "0.1.0"
description = "Quantum Federated Learning for Robotics Kinematics"
dependencies = [
    "flwr[simulation]",
    "pennylane",
    "torch",
    "numpy",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[tool.flwr.app]
publisher = "soaham"

[tool.flwr.app.components]
serverapp = "qfl_robotics.server_app:app"
clientapp = "qfl_robotics.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
